add_newline=false
format = """
[â”Œâ”€$username](red)
[â””â”€$directory$rust$package$git_branch> ](red)"""
[character]
error_symbol="[|â¯](red)"
success_symbol="[|â¯](white)"
[line_break]
disabled=true
[cmd_duration]
disabled=true
[directory]
style="white bold"
format="\\[[$path]($style)\\]"
truncation_length = 3
truncation_symbol = "â€¦/"
[username]
style_user="white bold"
disabled=false
show_always=true
format="(bold red)\\[[$user]($style)\\]"
[git_commit]
disabled=false
commit_hash_length = 4
#tag_symbol = "ğŸ”– "
[git_branch]
disabled=false
#symbol = "ğŸŒ± "
truncation_length = 10
truncation_symbol = ""
format = " on [$branch]($style)"
style = "bold white"

[git_status]
disabled=false
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
